### ISSUE TITLE
/wild

### ISSUE THREAD

**Issue by NGGNewGen** [nikoskon2003/WarpsPro#3]
Loving the plugin so far! Makes my life easier (warps wise :P)
Although the /wild part of the plugin does not seem to work, i set it up properly and i just dont get teleported, any reason why?

STEPS TO REPRODUCE THIS ISSUE:
1: Install the .phar file into the server
2: Restart the server
3: try to do the command /wild

**Comment by nikoskon2003** [comment]
Bug fixed!
