### ISSUE TITLE
add

### ISSUE THREAD

**Issue by mikeygio10** [nikoskon2003/WarpsPro#4]
add a way to set permissons for a warp

**Comment by nikoskon2003** [comment]
Can you explain it further?

**Comment by nikoskon2003** [comment]
I can intergrate permissions like this:
check if Player has a permission: warpspro.command.warp.<warp name> 
every player should have the permission, unless it is removed from another plugin, like PurePerms.
If you want a more complex system built-in the plugin, I could make it.
Please share your thoughts,
nikoskon

**Comment by mikeygio10** [comment]
yes if you could i would be great

**Comment by mikeygio10** [comment]
what i mean is. If i could set it so you can only teleport to a warp if you have the perm to do warpspro.command.warp. [Then the name of that warp] That would be awesome

**Comment by nikoskon2003** [comment]
You can remove warp permission from a player with this command in PurePerms:
/setuperm [username] -warpspro.command.warp[warpname]
You can remove warp permission from a group with this command in PurePerms:
/setgperm [groupname] -warpspro.command.warp[warpname]
In addition, players without the permission to warp, will not see that specific warp in the "/warp" command.

I have submitted the update to poggit.pmmp.io and hopefully it will be accepted soon!
Have a nice day,
nikoskon

**Comment by mikeygio10** [comment]
Thank you!
