### ISSUE TITLE
Permission not working

### ISSUE THREAD

**Issue by LegoFan48737** [nikoskon2003/WarpsPro#6]
the `warpspro.command.warp` permission isn't working. I've set it to Guest, Villager and Citizen ranks, none of which are able to use the /warp command (either directly, or via a Slapper). They get the error "You do not have permission to warp to Warps"  (with the warp name being "Warps").

**Comment by nikoskon2003** [comment]
Hello and thanks for reporing!
This is my mistake, while adding per-warp permissions, I overlooked the fact that someone may want to set warps open to anyone! I will fix this issue as soon as I can. For now a fix could be adding the permission to warp to specific warp. The permission would be: `warpspro.command.warp.['warp_name]'`
Thanks again and im sorry for the inconvenience caused.

**Comment by LegoFan48737** [comment]
Ahh ok thx, i ended up using a Portal (more in theme with the lobby anyway)
I'll set that permission for rn then, thx again

**Comment by provsnoobgaming** [comment]
This was happening to me also
till ilooked at this github issue i had no idea why it wasb't working

**Comment by provsnoobgaming** [comment]
I don't get it.
How do i setup perns what did you meant by ['warp_name]'

**Comment by LegoFan48737** [comment]
> I don't get it.
> How do i setup perns what did you meant by ['warp_name]'

Say your warp name is "Town"
Set the Permission `warpspro.command.warp.town` from what i understand. I never actually tested it (ended up using PortalsPE), but that should work.

**Comment by nikoskon2003** [comment]
So i will make a system where you can set the warp to be open or only for players with the permission. For now you will have to use (if you user pure perms) /setuperm <username> warpspro.command.warp.<warp name> , where <warpname> is the name of the warp. If you have a warp called "Town" you would do warpspro.command.warp.Town

**Comment by nikoskon2003** [comment]
Issue resolved.
You can now set a warp to be open to anyone by typing:
/warp edit <name> open true

Thank you,
nikoskon

**Comment by CtrlAltTr0ll** [comment]
The perm is still not working, I have a closed warp and gave my VIP permission to use it and it says they do not have permission.

/setuperm warpspro.command.warp.MineVIP

The warp is named MineVIP, and is closed.
